### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by n-rodriguez** [saltstack-formulas/collectd-formula#114]
Thank you!

**Comment by myoung34** [comment]
maybe? These formulas are mostly maintained by those who use them

**Comment by johnkeates** [comment]
Also, most maintenance is based on contributions from people that want certain changes. Another issue with this specific formula is that collectd isn't as hot as it used to be, there are a bunch of people that simply moved to Prometheus, Elastic's Beats system, or one of those NMS systems.

**Comment by n-rodriguez** [comment]
@myoung34 : only if they have commit right

> Also, most maintenance is based on contributions from people that want certain changes.

I know, I'm one of them ^^ (https://github.com/saltstack-formulas/collectd-formula/issues/92)
I was asking because this PR is opened since almost a year and still no answer :(

**Comment by myoung34** [comment]
> I know, I'm one of them ^^ (#92)

and

> Also, most maintenance is based on contributions from people that want certain changes.

Feel free to submit the contribution. Again to say what @johnkeates said, contributions are based on personal requirements. If you need #92 solved and it isnt solved yet, thats because no one else has needed it badly enough to contribute it. We all are working on many things, so unless I or someone else need it, we arent usually going to do it. That's just how community software works. If you still need #92 , feel free to submit a PR for it and it will likely get merged.

**Comment by n-rodriguez** [comment]
> If you still need #92 , feel free to submit a PR for it and it will likely get merged.

you mean like this one https://github.com/saltstack-formulas/collectd-formula/pull/77?

**Comment by myoung34** [comment]
Not linked to #92 or ever previously mentioned here, so please comment there to make that easier.
Also lets keep issues and PR's actionable, this ticket has no actions to take
